In [1]:
import cv2
from keras.models import load_model
import numpy as np
model = load_model('keras_model.h5')
cap = cv2.VideoCapture(0)
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

while True: 
    ret, frame = cap.read()
    resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
    image_np = np.array(resized_frame)
    normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
    data[0] = normalized_image
    prediction = model.predict(data)
    cv2.imshow('frame', frame)
    # Press q to close the window
    print(prediction)
    
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
            
# After the loop release the cap object
cap.release()
# Destroy all the windows
cv2.destroyAllWindows()

2022-03-14 16:34:51.745243: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


[[1.2979626e-14 2.1259650e-05 5.6916597e-06 9.9997306e-01]]
[[2.4089351e-09 1.6477437e-05 1.1250641e-12 9.9998355e-01]]
[[4.5391912e-11 2.6597728e-08 2.1066663e-13 1.0000000e+00]]
[[1.9051184e-12 1.9290496e-09 3.8474050e-11 1.0000000e+00]]
[[5.8972440e-14 1.4758439e-09 2.5472438e-13 1.0000000e+00]]
[[1.1458696e-11 1.1071011e-02 2.2084992e-02 9.6684396e-01]]
[[5.0510454e-09 8.4526378e-01 6.8470336e-09 1.5473627e-01]]
[[4.6627132e-08 6.7383730e-01 2.2686625e-11 3.2616261e-01]]
[[9.2390084e-10 9.8982996e-01 1.7392050e-11 1.0170037e-02]]
[[4.5849116e-10 4.3584820e-04 1.7215671e-04 9.9939203e-01]]
[[1.4215396e-13 3.8069635e-07 2.0617485e-11 9.9999964e-01]]
[[1.16358026e-11 7.41595542e-03 2.44573304e-08 9.92584109e-01]]
[[6.252335e-11 7.840019e-03 7.357275e-08 9.921598e-01]]
[[1.6956594e-09 1.0665837e-04 8.2365087e-10 9.9989331e-01]]
[[2.9911862e-09 3.1837800e-03 1.0411258e-07 9.9681610e-01]]
[[8.82174067e-09 1.08472705e-05 7.51601625e-09 9.99989152e-01]]
[[4.3596644e-11 1.9096356e-06 5.6514